import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {

  const router = useRouter();

  const [Data, setData] = useState('')

  const about = () => {
    router.push(`/about`)
  }

const input = (e) => {
  setData(e.target.value)
}

  const cari = (e) => {
    e.preventDefault()
    router.push(`/?cari=${Data}`);
  }

  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div>
        <h1>home</h1>
        <Link href="/about">
            <p>about link</p>
        </Link>
        <p className={styles.tester} onClick={about} >about onclick</p>
        <p>
          <form onSubmit={cari}>
            <input type="text" placeholder="cari" value={Data} onChange={input}  />
            <button type="submit">seacrh</button>
          </form>
        </p>
        <p>hasil seacrh</p>
        <p>{router.query.cari}</p>
        </div>

    </div>
  )
}
